/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "learning-gradle-with-java.h"
#include <cassert>

int main() {
    learning_gradle_with_java::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
