/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "learning-gradle-with-java.h"

std::string learning_gradle_with_java::Greeter::greeting() {
    return std::string("Hello, World!");
}
