/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef LEARNING_GRADLE_WITH_JAVA_H
#define LEARNING_GRADLE_WITH_JAVA_H

#ifdef _WIN32
#define LEARNING_GRADLE_WITH_JAVA_EXPORT_FUNC __declspec(dllexport)
#else
#define LEARNING_GRADLE_WITH_JAVA_EXPORT_FUNC
#endif

#include <string>

namespace learning_gradle_with_java {
    class Greeter {
        public:
        std::string LEARNING_GRADLE_WITH_JAVA_EXPORT_FUNC greeting();
    };
}

#endif
